name: '3:27'
favicon: null
layout_spectrum: 0.26342556765303016
typography_spectrum: 0.12879672413691878
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b0b0b0'
    - '#7e7e7e'
    - '#dfdfdf'
    - '#585858'
    - '#fefefe'
  brandStrength: 0.625
  lightness: 0.03289986844174564
  saturation: 0.7985751237720251
  rhythmicContrast: 0.43584426399320364
purpose: []
