name: '3:27'
favicon: null
layout_spectrum: 0.26342556765303016
typography_spectrum: 0.12879672413691878
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5103329599369317
  lightness: 0.03289986844174564
  saturation: 0.7985751237720251
  rhythmicContrast: 0.43584426399320364
purpose: []
